// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: period.proto

package period

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeriodHandler_GetPeriodById_FullMethodName = "/gogrpc.PeriodHandler/GetPeriodById"
	PeriodHandler_GetPeriodList_FullMethodName = "/gogrpc.PeriodHandler/GetPeriodList"
)

// PeriodHandlerClient is the client API for PeriodHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define RPC service
type PeriodHandlerClient interface {
	GetPeriodById(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodResponse, error)
	GetPeriodList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPeriodListResponse, error)
}

type periodHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewPeriodHandlerClient(cc grpc.ClientConnInterface) PeriodHandlerClient {
	return &periodHandlerClient{cc}
}

func (c *periodHandlerClient) GetPeriodById(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeriodResponse)
	err := c.cc.Invoke(ctx, PeriodHandler_GetPeriodById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *periodHandlerClient) GetPeriodList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPeriodListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeriodListResponse)
	err := c.cc.Invoke(ctx, PeriodHandler_GetPeriodList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeriodHandlerServer is the server API for PeriodHandler service.
// All implementations must embed UnimplementedPeriodHandlerServer
// for forward compatibility.
//
// Define RPC service
type PeriodHandlerServer interface {
	GetPeriodById(context.Context, *GetPeriodRequest) (*GetPeriodResponse, error)
	GetPeriodList(context.Context, *Empty) (*GetPeriodListResponse, error)
	mustEmbedUnimplementedPeriodHandlerServer()
}

// UnimplementedPeriodHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeriodHandlerServer struct{}

func (UnimplementedPeriodHandlerServer) GetPeriodById(context.Context, *GetPeriodRequest) (*GetPeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeriodById not implemented")
}
func (UnimplementedPeriodHandlerServer) GetPeriodList(context.Context, *Empty) (*GetPeriodListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeriodList not implemented")
}
func (UnimplementedPeriodHandlerServer) mustEmbedUnimplementedPeriodHandlerServer() {}
func (UnimplementedPeriodHandlerServer) testEmbeddedByValue()                       {}

// UnsafePeriodHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeriodHandlerServer will
// result in compilation errors.
type UnsafePeriodHandlerServer interface {
	mustEmbedUnimplementedPeriodHandlerServer()
}

func RegisterPeriodHandlerServer(s grpc.ServiceRegistrar, srv PeriodHandlerServer) {
	// If the following call pancis, it indicates UnimplementedPeriodHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeriodHandler_ServiceDesc, srv)
}

func _PeriodHandler_GetPeriodById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriodHandlerServer).GetPeriodById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeriodHandler_GetPeriodById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriodHandlerServer).GetPeriodById(ctx, req.(*GetPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeriodHandler_GetPeriodList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeriodHandlerServer).GetPeriodList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeriodHandler_GetPeriodList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeriodHandlerServer).GetPeriodList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PeriodHandler_ServiceDesc is the grpc.ServiceDesc for PeriodHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeriodHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gogrpc.PeriodHandler",
	HandlerType: (*PeriodHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeriodById",
			Handler:    _PeriodHandler_GetPeriodById_Handler,
		},
		{
			MethodName: "GetPeriodList",
			Handler:    _PeriodHandler_GetPeriodList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "period.proto",
}
