// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: period.proto

package period

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request Payload
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_period_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_period_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_period_proto_rawDescGZIP(), []int{0}
}

type GetPeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeriodId      uint32                 `protobuf:"varint,1,opt,name=periodId,proto3" json:"periodId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeriodRequest) Reset() {
	*x = GetPeriodRequest{}
	mi := &file_period_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeriodRequest) ProtoMessage() {}

func (x *GetPeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_period_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeriodRequest.ProtoReflect.Descriptor instead.
func (*GetPeriodRequest) Descriptor() ([]byte, []int) {
	return file_period_proto_rawDescGZIP(), []int{1}
}

func (x *GetPeriodRequest) GetPeriodId() uint32 {
	if x != nil {
		return x.PeriodId
	}
	return 0
}

// Response Payload
type GetPeriodListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*GetPeriodResponse   `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeriodListResponse) Reset() {
	*x = GetPeriodListResponse{}
	mi := &file_period_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeriodListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeriodListResponse) ProtoMessage() {}

func (x *GetPeriodListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_period_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeriodListResponse.ProtoReflect.Descriptor instead.
func (*GetPeriodListResponse) Descriptor() ([]byte, []int) {
	return file_period_proto_rawDescGZIP(), []int{2}
}

func (x *GetPeriodListResponse) GetData() []*GetPeriodResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPeriodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeriodId      uint32                 `protobuf:"varint,1,opt,name=periodId,proto3" json:"periodId,omitempty"`
	PeriodName    string                 `protobuf:"bytes,2,opt,name=periodName,proto3" json:"periodName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeriodResponse) Reset() {
	*x = GetPeriodResponse{}
	mi := &file_period_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeriodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeriodResponse) ProtoMessage() {}

func (x *GetPeriodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_period_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeriodResponse.ProtoReflect.Descriptor instead.
func (*GetPeriodResponse) Descriptor() ([]byte, []int) {
	return file_period_proto_rawDescGZIP(), []int{3}
}

func (x *GetPeriodResponse) GetPeriodId() uint32 {
	if x != nil {
		return x.PeriodId
	}
	return 0
}

func (x *GetPeriodResponse) GetPeriodName() string {
	if x != nil {
		return x.PeriodName
	}
	return ""
}

var File_period_proto protoreflect.FileDescriptor

const file_period_proto_rawDesc = "" +
	"\n" +
	"\fperiod.proto\x12\x06gogrpc\"\a\n" +
	"\x05Empty\".\n" +
	"\x10GetPeriodRequest\x12\x1a\n" +
	"\bperiodId\x18\x01 \x01(\rR\bperiodId\"F\n" +
	"\x15GetPeriodListResponse\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.gogrpc.GetPeriodResponseR\x04data\"O\n" +
	"\x11GetPeriodResponse\x12\x1a\n" +
	"\bperiodId\x18\x01 \x01(\rR\bperiodId\x12\x1e\n" +
	"\n" +
	"periodName\x18\x02 \x01(\tR\n" +
	"periodName2\x94\x01\n" +
	"\rPeriodHandler\x12D\n" +
	"\rGetPeriodById\x12\x18.gogrpc.GetPeriodRequest\x1a\x19.gogrpc.GetPeriodResponse\x12=\n" +
	"\rGetPeriodList\x12\r.gogrpc.Empty\x1a\x1d.gogrpc.GetPeriodListResponseB\x11Z\x0fprotobuf/periodb\x06proto3"

var (
	file_period_proto_rawDescOnce sync.Once
	file_period_proto_rawDescData []byte
)

func file_period_proto_rawDescGZIP() []byte {
	file_period_proto_rawDescOnce.Do(func() {
		file_period_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_period_proto_rawDesc), len(file_period_proto_rawDesc)))
	})
	return file_period_proto_rawDescData
}

var file_period_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_period_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: gogrpc.Empty
	(*GetPeriodRequest)(nil),      // 1: gogrpc.GetPeriodRequest
	(*GetPeriodListResponse)(nil), // 2: gogrpc.GetPeriodListResponse
	(*GetPeriodResponse)(nil),     // 3: gogrpc.GetPeriodResponse
}
var file_period_proto_depIdxs = []int32{
	3, // 0: gogrpc.GetPeriodListResponse.data:type_name -> gogrpc.GetPeriodResponse
	1, // 1: gogrpc.PeriodHandler.GetPeriodById:input_type -> gogrpc.GetPeriodRequest
	0, // 2: gogrpc.PeriodHandler.GetPeriodList:input_type -> gogrpc.Empty
	3, // 3: gogrpc.PeriodHandler.GetPeriodById:output_type -> gogrpc.GetPeriodResponse
	2, // 4: gogrpc.PeriodHandler.GetPeriodList:output_type -> gogrpc.GetPeriodListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_period_proto_init() }
func file_period_proto_init() {
	if File_period_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_period_proto_rawDesc), len(file_period_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_period_proto_goTypes,
		DependencyIndexes: file_period_proto_depIdxs,
		MessageInfos:      file_period_proto_msgTypes,
	}.Build()
	File_period_proto = out.File
	file_period_proto_goTypes = nil
	file_period_proto_depIdxs = nil
}
